// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1itQGXiuH9ivhf0vhyvAJfld7y9IYOWc',
    appId: '1:890269396379:web:db81ef0dc269ae7c80853e',
    messagingSenderId: '890269396379',
    projectId: 'horas-v3-76309',
    authDomain: 'horas-v3-76309.firebaseapp.com',
    storageBucket: 'horas-v3-76309.firebasestorage.app',
    measurementId: 'G-BLC2DLK04W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2FgFx-x-IILJBsRvLDuQfrL4FItufbE',
    appId: '1:890269396379:android:00a169c73a6f689d80853e',
    messagingSenderId: '890269396379',
    projectId: 'horas-v3-76309',
    storageBucket: 'horas-v3-76309.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1itQGXiuH9ivhf0vhyvAJfld7y9IYOWc',
    appId: '1:890269396379:web:e6aa99687d9f5ca080853e',
    messagingSenderId: '890269396379',
    projectId: 'horas-v3-76309',
    authDomain: 'horas-v3-76309.firebaseapp.com',
    storageBucket: 'horas-v3-76309.firebasestorage.app',
    measurementId: 'G-WNPLTE6QY5',
  );
}
